const concatenate = require("./concatenate.js"),
	flatten = require("./flatten.js"),
	flattenArray = require("./flatten-array.js"),
	flattenJSON = require("./flatten-json.js"),
	mathematics = require("./mathematics.js"),
	removeDuplicate = require("./remove-duplicate.js");
const version = 1;
module.exports = {
	changeCase: require("./change-case.js"),
	concat: concatenate,
	concatenate: concatenate,
	depth: require("./depth.js"),
	divide: require("./divide.js"),
	ensurePrefix: require("./ensure-prefix.js"),
	ensureSuffix: require("./ensure-suffix.js"),
	escapeRegularExpressionSpecialCharacter: require("./escape-regular-expression-special-character.js"),
	flat: flatten,
	flatArr: flattenArray,
	flatArray: flattenArray,
	flatJSON: flattenJSON,
	flatten: flatten,
	flattenArr: flattenArray,
	flattenArray: flattenArray,
	flattenJSON: flattenJSON,
	length: require("./length.js"),
	math: mathematics,
	mathematics: mathematics,
	merge: concatenate,
	nestify: require("./nestify.js"),
	parallelProcess: require("./parallel-process.js"),
	randomIndex: require("./random-index.js"),
	removeANSIEscapeCode: require("./remove-ansi-escape-code.js"),
	removeDuplicate: removeDuplicate,
	replaceholder: require("./replaceholder.js"),
	Replaceholder: require("./replaceholder-service.js"),
	reverseIndex: require("./reverse-index.js"),
	stringParse: require("./string-parse.js"),
	uniq: removeDuplicate,
	unique: removeDuplicate,
	v: version,
	ver: version,
	version: version
};
