const version = 1;
const concatenate = require("./concatenate.js"),
	flatten = require("./flatten.js"),
	mathematics = require("./mathematics.js"),
	removeDuplicate = require("./remove-duplicate.js"),
	toObject = require("./to-object.js");
module.exports = {
	changeCase: require("./change-case.js"),
	concat: concatenate,
	concatenate: concatenate,
	depth: require("./depth.js"),
	divide: require("./divide.js"),
	ensurePrefix: require("./ensure-prefix.js"),
	ensureSuffix: require("./ensure-suffix.js"),
	escapeRegularExpressionSpecialCharacter: require("./escape-regular-expression-special-character.js"),
	flat: flatten,
	flatten: flatten,
	length: require("./length.js"),
	math: mathematics,
	mathematics: mathematics,
	merge: concatenate,
	parallelProcess: require("./parallel-process.js"),
	removeANSIEscapeCode: require("./remove-ansi-escape-code.js"),
	removeDuplicate: removeDuplicate,
	reverseIndex: require("./reverse-index.js"),
	split: require("./split.js"),
	toObj: toObject,
	toObject: toObject,
	uniq: removeDuplicate,
	unique: removeDuplicate,
	v: version,
	ver: version,
	version: version
};
