const combination = require("./mathematics/combination.js"),
	cumulativeCombination = require("./mathematics/cumulative-combination.js"),
	cumulativePermutation = require("./mathematics/cumulative-permutation.js"),
	factorial = require("./mathematics/factorial.js"),
	greatestCommonDivisor = require("./mathematics/greatest-common-divisor.js"),
	hypotenuse = require("./mathematics/hypotenuse.js"),
	invertHypotenuse = require("./mathematics/invert-hypotenuse.js"),
	leastCommonMultiple = require("./mathematics/least-common-multiple.js"),
	mean = require("./mathematics/mean.js"),
	permutation = require("./mathematics/permutation.js");
module.exports = {
	average: mean,
	combination: combination,
	combine: combination,
	cumulativeCombination: cumulativeCombination,
	cumulativeCombine: cumulativeCombination,
	cumulativePermutation: cumulativePermutation,
	cumulativePermute: cumulativePermutation,
	factor: factorial,
	factorial: factorial,
	gcd: greatestCommonDivisor,
	gcf: greatestCommonDivisor,
	gcm: greatestCommonDivisor,
	greatestCommonDivisor: greatestCommonDivisor,
	greatestCommonFactor: greatestCommonDivisor,
	greatestCommonMeasure: greatestCommonDivisor,
	hcd: greatestCommonDivisor,
	hcf: greatestCommonDivisor,
	highestCommonDivisor: greatestCommonDivisor,
	highestCommonFactor: greatestCommonDivisor,
	hypot: hypotenuse,
	hypotenuse: hypotenuse,
	invertHypot: invertHypotenuse,
	invertHypotenuse: invertHypotenuse,
	lcm: leastCommonMultiple,
	leastCommonMultiple: leastCommonMultiple,
	lowestCommonMultiple: leastCommonMultiple,
	mean: mean,
	median: require("./mathematics/median.js"),
	nCr: combination,
	nPr: permutation,
	permutation: permutation,
	permute: permutation,
	scm: leastCommonMultiple,
	smallestCommonMultiple: leastCommonMultiple
};
