const mathematicsCombination = require("./mathematics/combination.js"),
	mathematicsCumulativeCombination = require("./mathematics/cumulative-combination.js"),
	mathematicsCumulativePermutation = require("./mathematics/cumulative-permutation.js"),
	mathematicsFactorial = require("./mathematics/factorial.js"),
	mathematicsGreatestCommonDivisor = require("./mathematics/greatest-common-divisor.js"),
	mathematicsHypotenuse = require("./mathematics/hypotenuse.js"),
	mathematicsInvertHypotenuse = require("./mathematics/invert-hypotenuse.js"),
	mathematicsLeastCommonMultiple = require("./mathematics/least-common-multiple.js"),
	mathematicsMean = require("./mathematics/mean.js"),
	mathematicsPermutation = require("./mathematics/permutation.js");
module.exports = {
	average: mathematicsMean,
	combination: mathematicsCombination,
	combine: mathematicsCombination,
	cumulativeCombination: mathematicsCumulativeCombination,
	cumulativeCombine: mathematicsCumulativeCombination,
	cumulativePermutation: mathematicsCumulativePermutation,
	cumulativePermute: mathematicsCumulativePermutation,
	factor: mathematicsFactorial,
	factorial: mathematicsFactorial,
	gcd: mathematicsGreatestCommonDivisor,
	gcf: mathematicsGreatestCommonDivisor,
	gcm: mathematicsGreatestCommonDivisor,
	greatestCommonDivisor: mathematicsGreatestCommonDivisor,
	greatestCommonFactor: mathematicsGreatestCommonDivisor,
	greatestCommonMeasure: mathematicsGreatestCommonDivisor,
	hcd: mathematicsGreatestCommonDivisor,
	hcf: mathematicsGreatestCommonDivisor,
	highestCommonDivisor: mathematicsGreatestCommonDivisor,
	highestCommonFactor: mathematicsGreatestCommonDivisor,
	hypot: mathematicsHypotenuse,
	hypotenuse: mathematicsHypotenuse,
	invertHypot: mathematicsInvertHypotenuse,
	invertHypotenuse: mathematicsInvertHypotenuse,
	lcm: mathematicsLeastCommonMultiple,
	leastCommonMultiple: mathematicsLeastCommonMultiple,
	lowestCommonMultiple: mathematicsLeastCommonMultiple,
	mean: mathematicsMean,
	median: require("./mathematics/median.js"),
	nCr: mathematicsCombination,
	nPr: mathematicsPermutation,
	permutation: mathematicsPermutation,
	permute: mathematicsPermutation,
	scm: mathematicsLeastCommonMultiple,
	smallestCommonMultiple: mathematicsLeastCommonMultiple
};
